# Generated by Django 2.1 on 2018-08-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('brand', models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('coreCount', models.IntegerField()),
                ('threadsCount', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('RAM_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=10)),
            ],
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='CPUsocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('GPU_ruler', models.CharField(choices=[('GeForce', 'GeForce'), ('Radeon', 'Radeon')], max_length=8)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('RAM', models.IntegerField()),
                ('RAM_type', models.CharField(choices=[('GDDR3', 'GDDR3'), ('GDDR4', 'GDDR4'), ('GDDR5', 'GDDR5')], max_length=8)),
                ('watts', models.IntegerField()),
                ('GPU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Parts.GPU')),
            ],
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='GraphicCardBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DIMM', 'DIMM'), ('SO-DIMM', 'SO-DIMM')], max_length=8)),
                ('RAM_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=8)),
                ('RAM_amount', models.IntegerField()),
                ('frequency', models.IntegerField()),
            ],
            bases=('Products.product',),
        ),
        migrations.AddField(
            model_name='graphiccard',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Parts.GraphicCardBrand'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Parts.CPUsocket'),
        ),
    ]
