# Generated by Django 2.1 on 2018-09-01 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motherboardinterface',
            name='name',
        ),
    ]
