# Generated by Django 2.1 on 2018-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='RAM_type',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR3', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='brand',
            field=models.CharField(choices=[('Intel', 'Intel'), ('AMD', 'AMD')], default='Intel', max_length=8),
        ),
        migrations.AlterField(
            model_name='graphiccard',
            name='GPU_ruler',
            field=models.CharField(choices=[('GeForce', 'GeForce'), ('Radeon', 'Radeon')], default='GeForce', max_length=8),
        ),
        migrations.AlterField(
            model_name='graphiccard',
            name='RAM_type',
            field=models.CharField(choices=[('GDDR3', 'GDDR3'), ('GDDR4', 'GDDR4'), ('GDDR5', 'GDDR5')], default='GDDR5', max_length=8),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='RAM_slot_count',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], default='2', max_length=2),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='RAM_type',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR3', max_length=8),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='formFactor',
            field=models.CharField(choices=[('MATX', 'MATX'), ('ATX', 'ATX')], default='MATX', max_length=5),
        ),
        migrations.AlterField(
            model_name='ram',
            name='RAM_type',
            field=models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], default='DDR3', max_length=8),
        ),
        migrations.AlterField(
            model_name='ram',
            name='type',
            field=models.CharField(choices=[('DIMM', 'DIMM'), ('SO-DIMM', 'SO-DIMM')], default='DIMM', max_length=8),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='memory_type',
            field=models.CharField(choices=[('SLC', 'SLC'), ('MLC', 'MLC'), ('TLC', 'TLC')], default='TLC', max_length=5),
        ),
    ]
