# Generated by Django 2.1 on 2018-09-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0002_remove_motherboardinterface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboardinterface',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Parts.InterfaceName'),
        ),
    ]
