# Generated by Django 2.1 on 2018-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0003_motherboardinterface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='formFactor',
            field=models.CharField(choices=[('MATX', 'MATX'), ('ATX', 'ATX'), ('UATX', 'UATX')], default='MATX', max_length=5),
        ),
    ]
