# Generated by Django 2.1 on 2018-08-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Parts', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('ram_amount', models.IntegerField()),
                ('hdd_amount', models.IntegerField()),
                ('ssd_amount', models.IntegerField()),
                ('CPU', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Parts.CPU')),
                ('graphic_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Parts.GraphicCard')),
            ],
            options={
                'verbose_name': '> Computer',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='ComputerInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='Computers.Computer')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('diagonal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resolution', models.CharField(choices=[('1920x1080', '1920x1080'), ('1366х768', '1366х768')], max_length=8)),
                ('matrix', models.CharField(choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA')], max_length=8)),
                ('ram_amount', models.IntegerField()),
                ('discreteGraphic', models.BooleanField(default=False)),
                ('gpu', models.CharField(default=None, max_length=20)),
                ('graphic_ram_amount', models.IntegerField(default=None)),
                ('hdd_amount', models.IntegerField(default=0)),
                ('ssd_amount', models.IntegerField(default=0)),
                ('emmc_amount', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': '> Laptop',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('core_count', models.CharField(choices=[('2', '2'), ('4', '4')], max_length=2)),
                ('thread_count', models.CharField(choices=[('4', '4'), ('8', '8')], default=None, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LaptopInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='Computers.Laptop')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Computers.InterfaceName')),
            ],
        ),
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Computers.LaptopBrand'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Computers.LaptopCPU'),
        ),
        migrations.AddField(
            model_name='computerinterface',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Computers.InterfaceName'),
        ),
    ]
