# Generated by Django 2.1 on 2018-08-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0004_auto_20180810_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('graphic_card_name', models.CharField(max_length=50)),
                ('graphic_card_ram_type', models.CharField(choices=[('GDDR3', 'GDDR3'), ('GDDR4', 'GDDR4'), ('GDDR5', 'GDDR5')], max_length=10)),
                ('ram_type', models.CharField(choices=[('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4')], max_length=10)),
                ('ram_amount', models.IntegerField()),
                ('hdd_amount', models.IntegerField()),
                ('ssd_amount', models.IntegerField()),
            ],
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cpu_core_count', models.IntegerField()),
                ('cpu_threads_count', models.IntegerField()),
                ('cpu_frequency', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='_CPU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Computers.CPU'),
        ),
        migrations.AddField(
            model_name='computer',
            name='graphic_card_gpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Computers.GPU'),
        ),
    ]
