# Generated by Django 2.1 on 2018-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='matrix',
            field=models.CharField(choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA')], max_length=12),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1920x1080'), ('1366х768', '1366х768')], max_length=12),
        ),
    ]
