# Generated by Django 2.1 on 2018-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0002_auto_20180812_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='matrix',
            field=models.CharField(choices=[('IPS', 'IPS'), ('TN', 'TN'), ('VA', 'VA')], default='IPS', max_length=12),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1920x1080'), ('1366х768', '1366х768')], default='1920x1080', max_length=12),
        ),
        migrations.AlterField(
            model_name='laptopcpu',
            name='core_count',
            field=models.CharField(choices=[('2', '2'), ('4', '4')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='laptopcpu',
            name='thread_count',
            field=models.CharField(choices=[('4', '4'), ('8', '8')], default='4', max_length=2),
        ),
    ]
