# Generated by Django 2.1 on 2018-08-14 13:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Computers', '0004_auto_20180814_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Computers.LaptopGPU'),
        ),
        migrations.AlterField(
            model_name='laptopgpu',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
