# Generated by Django 2.1 on 2018-08-16 14:17

import Main.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='noName', max_length=50)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=Main.models.corousel_path)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
