# Generated by Django 2.1 on 2018-08-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget'},
        ),
    ]
