# Generated by Django 2.1.4 on 2019-01-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_serviceorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='type',
        ),
    ]
