# Generated by Django 2.1.4 on 2019-01-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_serviceorder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='service_type',
            field=models.CharField(default='', max_length=64),
        ),
    ]
