# Generated by Django 2.1.4 on 2019-01-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_serviceorder_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceOrder',
        ),
    ]
