# Generated by Django 2.1 on 2018-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpusmartphone',
            name='core_count',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='fingerprint',
            field=models.CharField(default='нет', max_length=5),
        ),
    ]
