# Generated by Django 2.1 on 2018-08-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1920x1080'), ('2160х1080', '2160х1080'), ('1280x720', '1280x720'), ('1440x720', '1440x720'), ('1024x600', '1024x600')], default='2160х1080', max_length=12),
        ),
    ]
