# Generated by Django 2.1 on 2018-08-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0002_auto_20180812_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='fingerprint',
            field=models.CharField(choices=[('есть', 'есть'), ('нет', 'нет')], default='нет', max_length=10),
        ),
    ]
