# Generated by Django 2.1 on 2018-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0002_auto_20180820_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='operating_system',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], default='Android', max_length=20),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='android',
            field=models.CharField(blank=True, choices=[('6.0', '6.0'), ('7.0', '7.0'), ('7.1', '7.1'), ('8.0', '8.0'), ('8.1', '8.1')], default='8.1', max_length=4, null=True),
        ),
    ]
