# Generated by Django 2.1 on 2018-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0003_auto_20180812_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='front_camera',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
    ]
