# Generated by Django 2.1 on 2018-08-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0004_auto_20180813_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='front_camera',
        ),
    ]
