# Generated by Django 2.1 on 2018-08-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart', '0006_smartphone_front_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='android',
            field=models.CharField(choices=[('6.0', '6.0'), ('7.0', '7.0'), ('7.1', '7.1'), ('8.0', '8.0'), ('8.1', '8.1')], default='8.1', max_length=4),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='matrix',
            field=models.CharField(choices=[('IPS', 'IPS'), ('OLED', 'OLED'), ('TFT', 'TFT')], default='IPS', max_length=6),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='net',
            field=models.CharField(choices=[('3G', '3G'), ('4G', '4G')], default='4G', max_length=3),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(choices=[('1920x1080', '1920x1080'), ('2160х1080', '2160х1080'), ('1280x720', '1280x720'), ('1440x720', '1440x720')], default='2160х1080', max_length=12),
        ),
    ]
