# Generated by Django 2.1 on 2018-08-12 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('earbubs_type', models.CharField(choices=[('Вставные(вакуумные)', 'Вставные(вакуумные)'), ('Охватывающие', 'Охватывающие')], max_length=20)),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('Jack 3.5', 'Jack 3.5'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='Провод', max_length=15)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('resistance', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Headphone',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='HeadphoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('interface', models.CharField(choices=[('USB', 'USB'), ('PS/2', 'PS/2')], default='USB', max_length=5)),
                ('type', models.CharField(choices=[('Мембрана', 'Мембрана'), ('Механическая', 'Механическая')], default='Мембрана', max_length=15)),
                ('connection_type', models.CharField(choices=[('Провод', 'Провод'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='Провод', max_length=15)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('key_count', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Keyboard',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='KeyboardBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('interface', models.CharField(choices=[('USB', 'USB'), ('PS/2', 'PS/2')], default='USB', max_length=5)),
                ('connection_type', models.CharField(choices=[('Провод', 'Провод'), ('Беспроводная', 'Беспроводная')], default='Провод', max_length=15)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('max_dpi', models.IntegerField()),
                ('button_count', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Mouse',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='MouseBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.MouseBrand'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.KeyboardBrand'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.KeyboardBrand'),
        ),
    ]
