# Generated by Django 2.1 on 2018-08-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('earbubs_type', models.CharField(choices=[('Вставные(вакуумные)', 'Вставные(вакуумные)'), ('Охватывающие', 'Охватывающие')], default='Охватывающие', max_length=50)),
                ('connection_type', models.CharField(choices=[('USB', 'USB'), ('Jack 3.5', 'Jack 3.5'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='Jack 3.5', max_length=30)),
                ('microphone', models.CharField(choices=[('есть', 'есть'), ('нет', 'нет')], default='есть', max_length=10)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('resistance', models.IntegerField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Headphone',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='HeadphoneBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('interface', models.CharField(choices=[('USB', 'USB'), ('PS/2', 'PS/2'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='USB', max_length=20)),
                ('type', models.CharField(choices=[('Мембрана', 'Мембрана'), ('Механическая', 'Механическая')], default='Мембрана', max_length=50)),
                ('illumination', models.CharField(choices=[('Нет', 'Нет'), ('RGB', 'RGB'), ('Монотонная', 'Монотонная')], default='RGB', max_length=20)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('key_count', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Keyboard',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='KeyboardBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('interface', models.CharField(choices=[('USB', 'USB'), ('PS/2', 'PS/2'), ('Bluetooth', 'Bluetooth'), ('2.4Ghz', '2.4Ghz')], default='USB', max_length=20)),
                ('wire_length', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=2, null=True)),
                ('max_dpi', models.IntegerField()),
                ('button_count', models.IntegerField()),
                ('weight', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': '> Mouse',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='MouseBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=50)),
                ('channels', models.CharField(choices=[('2.0', '2.0'), ('2.1', '2.1'), ('5.1', '5.1'), ('7.1', '7.1')], default='2.0', max_length=10)),
                ('power', models.IntegerField()),
                ('power_output', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('waterproof', models.CharField(choices=[('есть', 'есть'), ('нет', 'нет')], default='нет', max_length=10)),
                ('microsd', models.CharField(choices=[('есть', 'есть'), ('нет', 'нет')], default='нет', max_length=10)),
                ('microphone', models.CharField(choices=[('есть', 'есть'), ('нет', 'нет')], default='нет', max_length=10)),
            ],
            options={
                'verbose_name': '> Speaker',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='SpeakerBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerFrequencyDiapason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerInterfaceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='speakerinterface',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CompPeripherals.SpeakerInterfaceName'),
        ),
        migrations.AddField(
            model_name='speakerinterface',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='CompPeripherals.Speaker'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.SpeakerBrand'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='frequency_diapason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.SpeakerFrequencyDiapason'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.MouseBrand'),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.KeyboardBrand'),
        ),
        migrations.AddField(
            model_name='headphone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CompPeripherals.KeyboardBrand'),
        ),
    ]
