# Generated by Django 2.1 on 2018-08-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20180812_2255'),
        ('CompPeripherals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mousepad',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Длина (см)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Толщина (мм)')),
            ],
            options={
                'verbose_name': '> Mousepad',
            },
            bases=('Products.product',),
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='connection_type',
        ),
        migrations.AlterField(
            model_name='headphone',
            name='connection_type',
            field=models.CharField(choices=[('USB', 'USB'), ('Jack 3.5', 'Jack 3.5'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='Провод', max_length=30),
        ),
        migrations.AlterField(
            model_name='headphone',
            name='earbubs_type',
            field=models.CharField(choices=[('Вставные(вакуумные)', 'Вставные(вакуумные)'), ('Охватывающие', 'Охватывающие')], max_length=50),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='interface',
            field=models.CharField(choices=[('USB', 'USB'), ('PS/2', 'PS/2'), ('Провод', 'Провод'), ('Bluetooth', 'Bluetooth'), ('2.4 Ghz', '2.4 Ghz')], default='USB', max_length=20),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='type',
            field=models.CharField(choices=[('Мембрана', 'Мембрана'), ('Механическая', 'Механическая')], default='Мембрана', max_length=50),
        ),
    ]
