# Generated by Django 2.1 on 2018-08-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompPeripherals', '0003_keyboard_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyboard',
            name='type',
            field=models.CharField(choices=[('Мембрана', 'Мембрана'), ('Механическая', 'Механическая'), ('Резиновая', 'Резиновая')], default='Мембрана', max_length=50),
        ),
    ]
