# Generated by Django 2.1 on 2018-08-14 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_product_link'),
        ('CompPeripherals', '0003_auto_20180814_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mousepad',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Mousepad',
        ),
    ]
