# Generated by Django 2.1 on 2018-08-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompPeripherals', '0004_auto_20180818_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='power',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='power_output',
        ),
    ]
