# Generated by Django 2.1 on 2018-08-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompPeripherals', '0005_auto_20180829_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='power',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='speaker',
            name='power_output',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
