# Generated by Django 2.1 on 2018-08-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompPeripherals', '0006_auto_20180829_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='power',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='power_output',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
