# Generated by Django 2.1 on 2018-08-14 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0008_product_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mousepad',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.Product')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Длина (см)')),
                ('width', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Ширина (см)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Толщина (мм)')),
            ],
            options={
                'verbose_name': '> Mousepad',
            },
            bases=('Products.product',),
        ),
    ]
