# Generated by Django 2.1 on 2018-08-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accessories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousepad',
            name='product_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='mousepad', serialize=False, to='Products.Product'),
        ),
    ]
