# Generated by Django 2.1 on 2018-08-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='goods',
        ),
        migrations.AlterField(
            model_name='order',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='person_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
