# Generated by Django 2.1 on 2018-08-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
