# Generated by Django 2.1 on 2018-08-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20180813_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='ru.aliexpress.com'),
        ),
    ]
