# Generated by Django 2.1 on 2018-08-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slide_num',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
