# Generated by Django 2.1 on 2018-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_color_slide_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
